### ISSUE TITLE
How to add httpAdditionalHeaders on sessionConfig?

### ISSUE THREAD

**Issue by firdarinoa** [kudoleh/SENetworking#1]
Hi! I need to add "Authorization" header which considered reserved HTTP headers according to [Apple Documentation](https://developer.apple.com/documentation/foundation/nsurlrequest#1776617). How can I add custom session configuration to add http additional headers? Thank you in advance!

**Comment by kudoleh** [comment]
Hello ideally authentication logic should be outside of Networking module.

 https://github.com/kudoleh/iOS-Modular-Architecture#including-authentication-module-initial-scaling

Sent from my iPhone

On 9. Feb 2023, at 02:25, Firda Sahidi ***@***.***> wrote:

﻿

Hi! I need to add "Authorization" header which considered reserved HTTP headers according to Apple Documentation<https://developer.apple.com/documentation/foundation/nsurlrequest#1776617>. How can I add custom session configuration to add http additional headers? Thank you in advance!

**Comment by firdarinoa** [comment]
thank you!
